// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_APIKEY'] ?? '',
    appId: '1:444558160448:web:ca36ef70fec131f4a965a5',
    messagingSenderId: '444558160448',
    projectId: 'chat-example-93e46',
    authDomain: 'chat-example-93e46.firebaseapp.com',
    storageBucket: 'chat-example-93e46.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_APK'] ?? '',
    appId: '1:444558160448:android:1e7ba784c958d3b1a965a5',
    messagingSenderId: '444558160448',
    projectId: 'chat-example-93e46',
    storageBucket: 'chat-example-93e46.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_APK'] ?? '',
    appId: '1:444558160448:ios:e8a54e5ceb359bd8a965a5',
    messagingSenderId: '444558160448',
    projectId: 'chat-example-93e46',
    storageBucket: 'chat-example-93e46.firebasestorage.app',
    iosBundleId: 'com.example.chatWithFirebase',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_APK'] ?? '',
    appId: '1:444558160448:ios:e8a54e5ceb359bd8a965a5',
    messagingSenderId: '444558160448',
    projectId: 'chat-example-93e46',
    storageBucket: 'chat-example-93e46.firebasestorage.app',
    iosBundleId: 'com.example.chatWithFirebase',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WINDOWS_APK'] ?? '',
    appId: '1:444558160448:web:52f721cc2ba7de7ba965a5',
    messagingSenderId: '444558160448',
    projectId: 'chat-example-93e46',
    authDomain: 'chat-example-93e46.firebaseapp.com',
    storageBucket: 'chat-example-93e46.firebasestorage.app',
  );
}
